export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_CURRENTLY_PLAYING = 'SET_CURRENTLY_PLAYING';
export const SET_DEVICES = 'SET_DEVICES';
export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_VENUE = 'SET_VENUE';

export const VOTE_DOWN = 'VOTE_DOWN';
export const VOTE_UP = 'VOTE_UP';
